
###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=eli1

###

GET http://localhost:3000/post/625496d9ef24648b63b74ae0

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message" : "this is my first message",
    "sender" : "eli1"
}

